### ISSUE TITLE
App cuts parts of repeated voice when saving of recordings is enabled

### ISSUE THREAD

**Issue by tekk** [allebb/pirrot#20]
Hi,
first of all, thanks for this excellent project. It is awesome what can be done with PHP. :+1:  I appreciate your effort invested into this awesome work.
Let me explain my issue.
I'm experiencing this issue from the very beginning of the installation (repeater is running RPi Zero W, and it's live for around 1y, 24/7). Now I noticed that when I disable recording, it behaves normally.
It's hard to describe this sound "artefact". It's like the repeated voice starts playing normally but has "cutouts" in it. There are missing parts.
Could you please help me with that?
Any help is much appreciated.

**Comment by allebb** [comment]
Hey tekk,

Firstly sorry for the delay in getting back to you, I never saw this issue raised back in January until last week (I sent you an email too!)

I've just released a new version of Pirrot (1.0.4), I've make a few changes and includes some dependency updates too.

Personally, I've not been able to replicate your issue on my Raspberry Pi 3 (and all works fine) and can only assume if you're still having issues that it could be the Pi Zero W hardware that you're using? - maybe it's not got enough system resources to sustain long audio recordings?

Maybe you could try running ``htop`` when testing? - That may indicate that the memory is being fully utilised?

If I had a Pi Zero W I'd attempt to reproduce it but unfortunately I don't :(

**Comment by allebb** [comment]
Just realised whilst going through these issues that this is probably now fixed by your PR a few months ago (https://github.com/allebb/pirrot/commit/5434dd67e038a57ed830456c1e379dbfaeeee3e3).

I've just ordered a Raspberry Pi Zero W so plan to test and update and further optimise the project over the next couple of weeks 👍 

Feel free to re-open this issue if the recording performance on the RPi Zero W is still not great and I will do further tests when my RPi Zero W arrives next week.
